import Head from 'next/head'
import { FC } from 'react'
import Banner from '../components/banner/Banner'
import SectionCards from '../components/card/SectionCards'
import NavBar from '../components/nav/NavBar'

import videos from '../data/videos.json'

import { getPopularVideos, getVideos } from '../lib/videos'

import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export type Video = {
  id: string
  title: string
  imgUrl: string
}

export type HomeProps = {
  disneyVideos: Video[]
  productivityVideos: Video[]
  travelVideos: Video[]
  popularVideos: Video[]
}

export const getServerSideProps = async () => {
  const disneyVideos: Video[] = await getVideos('disney trailer')
  console.log(Date.now(), 'start')
  console.log('making request for disney')
  const productivityVideos: Video[] = await getVideos('productivity')
  console.log('making request for productivity')
  const travelVideos: Video[] = await getVideos('travel')
  console.log('making request for travel')
  const popularVideos: Video[] = await getPopularVideos()
  console.log('making request for popular')
  console.log(Date.now(), 'end')

  return {
    props: {
      disneyVideos,
      productivityVideos,
      travelVideos,
      popularVideos,
    },
  }
}

const Home: FC<HomeProps> = ({
  disneyVideos,
  productivityVideos,
  travelVideos,
  popularVideos,
}) => {
  return (
    <>
      <main className={styles.container}>
        <Head>
          <title>Netflix Clone</title>
          <meta
            name='description'
            content='Generated by create next app'
          />
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1'
          />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <NavBar />
          <Banner
            title='Clifford the red dog'
            subTitle='a very cute dog'
            imgUrl='/static/clifford.webp'
          />

          <div className={styles.sectionWrapper}>
            <SectionCards
              title='Disney'
              videos={disneyVideos}
              // videos={videos.items}
              size='large'
            />

            <SectionCards
              title='Travel'
              videos={travelVideos}
              // videos={videos.items}
              size='small'
            />

            <SectionCards
              title='Productivity'
              videos={productivityVideos}
              // videos={videos.items}
              size='medium'
            />

            <SectionCards
              title='Popular'
              videos={popularVideos}
              // videos={videos.items}
              size='small'
            />
          </div>
        </main>
      </main>
    </>
  )
}

export default Home
